require:
  - rubocop-minitest
  - standard

inherit_gem:
  rubocop-minitest: config/default.yml
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
  TargetRubyVersion: "2.7"
