version: '3.6'
services:
  test:
    image: ruby:2.6
    command: sh -c "rm -f Gemfile.lock && bundle install && bin/run_tests"
    depends_on:
      - mysql56
      - mysql57
      - mysql80
      - pg95
      - pg10
      - pg11
      - pg12
    working_dir: /app
    environment:
      AR_VERSION: 6.0 # other option is 5.2
    volumes:
      - bundle:/usr/local/bundle
      - .:/app
  test_ruby_2_5:
    image: ruby:2.5
    command: sh -c "rm -f Gemfile.lock && bundle install && bin/run_tests"
    depends_on:
      - mysql56
      - mysql57
      - mysql80
      - pg95
      - pg10
      - pg11
      - pg12
    working_dir: /app
    environment:
      AR_VERSION: 6.0 # other option is 5.2
    volumes:
      - bundle:/usr/local/bundle
      - .:/app

  mysql56:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --innodb-large-prefix --innodb-file-format=barracuda
    healthcheck:
      test:  mysql --password=password -e "show databases;"
  mysql57:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test:  mysql --password=password -e "show databases;"
  mysql80:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test:  mysql --password=password -e "show databases;"
  pg95:
    image: postgres:9.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data
      POSTGRES_DB: db
    healthcheck:
      test: echo "\\l" | psql -U postgre
  pg10:
    image: postgres:10
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data
      POSTGRES_DB: db
    healthcheck:
      test: echo "\\l" | psql -U postgre
  pg11:
    image: postgres:11
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data
      POSTGRES_DB: db
    healthcheck:
      test: echo "\\l" | psql -U postgre
  pg12:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data
      POSTGRES_DB: db
    healthcheck:
      test: echo "\\l" | psql -U postgre
volumes:
  bundle:
