---
name: Linting
on: push
jobs:
  standardrb:
    env:
      AR_VERSION: "5.2"
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - run: bundle exec standardrb
