---
name: Tests on the "main" branch of Rails

on:
  schedule:
    - cron: '15 8 * * MON'
  workflow_dispatch:

jobs:
  test:
    name: ActiveRecord main / Ruby 3.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose run test
        env:
          RUBY_VERSION: "3.3"
          AR_VERSION: "main"
