---
name: Tests

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tests:
    name: ActiveRecord ${{ matrix.activerecord-version }} / Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        activerecord-version: ["6.0", "6.1", "7.0", "7.0.5", "7.1"]
        ruby-version: ["2.7", "3.0", "3.1", "3.2"]
        include:
          - {activerecord-version: "5.2", ruby-version: "2.7"}
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose run test
        env:
          RUBY_VERSION: ${{ matrix.ruby-version }}
          AR_VERSION: ${{ matrix.activerecord-version }}
