---
name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        activerecord-version: ["5.2", "6.0", "6.1"]
        ruby-version: ["2.6", "2.7", "3.0"]
        exclude:
          - activerecord-version: "5.2"
            ruby-version: "3.0"
    steps:
      - uses: actions/checkout@v2
      - name: Test ActiveRecord ${{ matrix.activerecord-version }} and Ruby ${{ matrix.ruby-version }}
        run: RUBY_VERSION=${{ matrix.ruby-version }} docker-compose run -e AR_VERSION=${{ matrix.activerecord-version }} test
